28/10/22 (12:33:43) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
01/11/22 (01:51:43) | ERROR: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zidbon/.config/bpytop/themes'
